### ISSUE TITLE
How to access user object in Cloud Code

### ISSUE THREAD

**Issue by davidrichard23** [andrewimm/parse-lite#11]
I need access to the user object that calls the cloud function but request.user is always undefined. I'm calling the cloud function using: 

`Cloud(app, 'cloudFunctionName', {sessionToken: sessionToken})`

Looking at the source, it looks like Cloud() doesn't have an AuthOptions parameter. How can I access the user object?

**Comment by andrewimm** [comment]
Added auth options as a fourth parameter to Cloud. You can now call the function with the following:

`Cloud(app, 'cloudFunctionName', functionParams, {sessionToken: TOKEN})`

Will bump npm version numbers and republish

**Comment by davidrichard23** [comment]
Awesome, thanks!
