### ISSUE TITLE
modify the way to build a resource string

### ISSUE THREAD

**Issue by ValeriyKliuk** [andrewimm/parse-lite#2]
Hi, Thanks for your libraries ;)
I am testing the parse-lite on the localhost and getting error "Unable to connect to the server".
It is Ionic2 application and I am trying to reach a Parse-server running on my dev machine

``` javascript
import {App, Query} from 'parse-lite';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
   app = new App({
    host: "http://localhost:1337/parse", // Required
    applicationId: "myAppId" // Required
  }); 
```

The log is saying that my URL is "http://http//classes/Rooms/HQUHuf1tDA" Failed to load resource: Aucun serveur ayant le nom d’hôte précisé n’a pu être trouvé.

When I have changed it to  

``` javascript
  app = new App({
    host: "localhost:1337/parse", // Required
    applicationId: "myAppId" // Required
  }); 
```

got this one:
https://localhost:1337/parse/classes/Rooms/HQUHuf1tDA Failed to load resource: Une erreur SSL s’est produite et il est impossible d’établir une connexion sécurisée avec le serveur.

I hope it is clear what is going on here ;)
Val

**Comment by andrewimm** [comment]
Hi there,

Thanks for testing this out, but parse-lite is not quite ready for production (which is why I haven't finished documenting it).
The library defaults to using https for everything. To disable https, you need to explicitly override it by passing an option to `App()`:

```
app = new App({
  host: 'localhost:1337/parse',
  https: false,
  // ... other options
});
```

**Comment by andrewimm** [comment]
There does appear to be a bug in `ibeam`, the library used for HTTP connections. It shouldn't create that string with `http://` twice. I'll take a look at that.

**Comment by ValeriyKliuk** [comment]
Perfect!
Thank you very much for the quick response!
