### ISSUE TITLE
403 - unauthorised error

### ISSUE THREAD

**Issue by alioguzhan** [andrewimm/parse-lite#5]
Hi Andrew,

```
const app = new App({
    host: 'http://123.123.12.1:1337/bb', // replaced ip address
    applicationId: 'app12345',
    masterKey: 'master12345'
});
```

This is my code to initialize App. And i am trying to Query inside componentDidMount:

```
componentDidMount() {
        console.log('app: ', app);
        Query.find(app, 'Message', Query.emptyQuery()).then((items) => {
            console.log('items: ', items);
        }, (err) => {
            console.log('err: ', err);
        });    
    }
```

But it falls down to error handler and returns: `403 - unauthorized error`. 

I can query with these credentials over `curl`  without any problem. But inside app, not working. 

Do you have any idea?

**Comment by alioguzhan** [comment]
Found the issue. In `App.js` i disabled `useMasterKey` control and it worked:

```
// if (options.useMasterKey) {
        if (this._MasterKey) {
          json._MasterKey = this._MasterKey;
        } else {
          throw new Error('Cannot use the master key. It has not been provided.');
        }
// }
```
Here is the related file and line:
[https://github.com/andrewimm/parse-lite/blob/master/src/App.js#L53](https://github.com/andrewimm/parse-lite/blob/master/src/App.js#L53)

But AFAIK, `masterKey` should not be required in client sdks. Is this something related with my setup or library itself?

**Comment by andrewimm** [comment]
As noted on the PR, this is by design. Authentication is performed on a per-request basis, rather than globally. To authenticate a query find, it should look like the following:

```
Query.find(app, 'message', Query.emptyQuery(), {useMasterKey: true}).then(...
```
